CREATE DATABASE IF NOT EXISTS hourglass;
USE hourglass;
CREATE TABLE IF NOT EXISTS Subject(ID INT AUTO_INCREMENT, Name VARCHAR(255),Subject_Code VARCHAR(255), Enrolled_Students INT, Start_Date DATE, End_Date DATE, PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS Class(ID INT AUTO_INCREMENT, Name VARCHAR(255), Grade VARCHAR(255), Department VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS Room(ID INT AUTO_INCREMENT, Room_Nr VARCHAR(255), Total_Seats INT, PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS Lecturer(ID INT AUTO_INCREMENT, Name VARCHAR(255), Email VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS Subject_Lecturer(Subject_ID INT NOT NULL, Lecturer_ID INT NOT NULL, PRIMARY KEY(Subject_ID, Lecturer_ID), FOREIGN KEY (Subject_ID) REFERENCES Subject(ID), FOREIGN KEY (Lecturer_ID) REFERENCES Lecturer(ID));
CREATE TABLE IF NOT EXISTS Class_Subject(Subject_ID INT NOT NULL, Class_ID INT NOT NULL, PRIMARY KEY(Subject_ID, Class_ID), FOREIGN KEY (Subject_ID) REFERENCES Subject(ID), FOREIGN KEY (Class_ID) REFERENCES Class(ID));